name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - scikit-learn=1.3.0
  - pandas
  - numpy=1.26.4
  - psutil
  - lz4
  - scipy=1.11.1
  - pip:
      - mlflow==2.19.0
      - cloudpickle==2.2.1
      - pathlib==1.0.1
