name: Train Model on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env 
        auto-activate-base: false
        auto-update-conda: true
        use-mamba: true

    - name: Install MLflow CLI
      run: pip install mlflow

    - name: Run MLflow Project
      working-directory: MLProject
      run: mlflow run . --env-manager=local
